# kubectl create secret generic postgres-secret \
#   --from-literal=database_uri='postgresql://postgres:password@postgres:5432/products_db'

# data content:
# database_password: 'password'
# database_uri: 'postgresql://postgres:password@postgres:5432/products_db'


---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
data:
  database_password: cGFzc3dvcmQ=
  database_uri: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzOjU0MzIvcHJvZHVjdHNfZGI=