apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cd-listener-release
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-release
      interceptors:
        - ref:
            name: cel
          params:
          - name: filter
            value: "body.action == 'published'"
        - ref:
            name: "github"
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
          - name: "eventTypes"
            value: ["release"]
      bindings:
        - ref: cd-binding-release
      template:
        ref: cd-template

---

apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: cd-binding-release
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.clone_url)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-revision
    # use release tag name
    value: $(body.release.tag_name)
  - name: git-ref
    # use release tag name
    value: $(body.release.tag_name)