apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cd-listener-push
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-push
      bindings:
        - ref: cd-binding-push
      template:
        ref: cd-template


---

apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: cd-binding-push
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.clone_url)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-revision
    # use release tag name
    value: $(body.head_commit.id)
  - name: git-ref
    # use release tag name
    value: $(body.head_commit.id)
  
