apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: cd-binding
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.clone_url)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-revision
    # use release tag name
    value: $(body.release.tag_name)
  - name: git-ref
    # use release tag name
    value: $(body.release.tag_name)
  
