apiVersion: v1
kind: Namespace
metadata:
  name: devops-products
  labels:
    name: products

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: devops-products
  name: pipeline-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
